[package]
name = "contact"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"


[dependencies]
deep_space = {git = "https://github.com/althea-net/deep_space/", rev = "fb6495c72882376c6bb43f3ba7e891716564f954", features = ["peggy", "key_import"]}
#deep_space = {path = "../deep_space"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
actix-web = {version = "2.0", features=["openssl"]}
log = "0.4"
num256 = "0.2"
clarity = "0.1"

[dev-dependencies]
rand = "0.7"
actix = "0.9"